name: CI for Motolog App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend - Install & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: backend-npm-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            backend-npm-

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (server)
        run: npm install
        working-directory: ./server

      - name: Lint backend (optional)
        run: npm run lint
        working-directory: ./server
        continue-on-error: true

  frontend:
    name: Frontend - Build & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: frontend-npm-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            frontend-npm-

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Root dependencies
        run: npm install

      - name: Install dependencies (client)
        run: npm install
        working-directory: ./client

      - name: Lint frontend (optional)
        run: npm run lint
        working-directory: ./client
        continue-on-error: true

      - name: Build frontend
        run: npm run build
        working-directory: ./client
