name: Deploy to EC2

on:
  push:
    branches: [main] # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      - name: SSH & Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2-USER }}@${{ secrets.EC2-HOST }} << 'EOF'
            cd motolog-backend
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF
