name: Deploy to EC2

on:
  push:
    branches: [main] # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH & Deploy
        run: |
         ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
         echo "📂 Changing to backend directory"
         cd /home/ubuntu/motolog/server

         echo "🧹 Cleaning untracked files"
         git reset --hard
         git clean -fd

         echo "🔄 Pulling latest code"
         git pull origin main

         echo "🧼 Stopping existing container"
         docker-compose down

         echo "🔧 Rebuilding and restarting backend"
         docker-compose build --no-cache
         docker-compose up -d
       EOF
